import React from 'react';
import { Bell, RefreshCw, ShieldCheck, Sparkles, AlertCircle } from 'lucide-react';

/**
 * CustomerRecoveryNotification Component — RecoverAI M5 Page 2 Part 1
 * Customer-facing in-app recovery notification card.
 * 
 * STRICT BOUNDARY:
 * - Displays in-app simulated notification only.
 * - Retry Payment CTA navigates/resets to payment starting point without auto-submitting.
 */
export function CustomerRecoveryNotification({ notification, onRetryPayment }) {
  if (!notification) return null;

  const formattedAmount = new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: notification.currency || 'INR',
    maximumFractionDigits: 0
  }).format(notification.amount || 2000);

  return (
    <div className="rounded-xl border border-amber-900/60 bg-amber-950/20 p-5 text-left space-y-4 relative z-10">
      
      {/* Header Badges */}
      <div className="flex items-center justify-between border-b border-amber-900/40 pb-2.5 flex-wrap gap-2">
        <span className="text-xs font-semibold text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
          <Bell className="h-4 w-4 text-amber-400" />
          RecoverAI Recovery Notification
        </span>
        <div className="flex items-center gap-2">
          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded text-[10px] font-bold bg-amber-950 text-amber-300 border border-amber-800/80">
            <Sparkles className="h-3 w-3 text-amber-400" />
            Generated by RecoverAI
          </span>
          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded text-[10px] font-extrabold bg-slate-900 text-amber-400 border border-amber-800/80">
            Action: {notification.recommendedAction}
          </span>
        </div>
      </div>

      <div className="space-y-4 text-xs">
        {/* Notification Title & User-Friendly Message */}
        <div className="bg-slate-950/70 p-4 rounded-lg border border-amber-900/40 space-y-2">
          <div className="flex items-center gap-2">
            <AlertCircle className="h-4 w-4 text-amber-400 shrink-0" />
            <h4 className="text-sm font-bold text-white tracking-tight">{notification.title}</h4>
          </div>
          <p className="text-amber-200/90 leading-relaxed font-medium text-xs sm:text-sm">
            {notification.message}
          </p>
        </div>

        {/* Product & Payment Context Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <div className="bg-slate-950/60 p-3 rounded-lg border border-slate-800 min-w-0 sm:col-span-2">
            <span className="text-slate-500 text-[10px] font-semibold uppercase tracking-wider block mb-0.5">Program</span>
            <span className="font-bold text-white text-xs sm:text-sm block truncate">{notification.productName}</span>
          </div>

          <div className="bg-slate-950/60 p-3 rounded-lg border border-slate-800 min-w-0">
            <span className="text-slate-500 text-[10px] font-semibold uppercase tracking-wider block mb-0.5">Amount</span>
            <span className="font-bold text-amber-300 text-xs sm:text-sm whitespace-nowrap block">{formattedAmount}</span>
          </div>
        </div>

        {/* Action Explanation */}
        <div className="bg-amber-950/30 p-3 rounded-lg border border-amber-800/50 flex items-center justify-between flex-wrap gap-2">
          <div>
            <span className="text-[10px] font-semibold text-amber-300 uppercase tracking-wide block">Reason</span>
            <span className="text-amber-200 font-medium text-xs">{notification.reason}</span>
          </div>
        </div>

        {/* Retry Payment CTA Button */}
        <button
          type="button"
          onClick={onRetryPayment}
          className="w-full px-5 py-3.5 rounded-xl bg-gradient-to-r from-amber-600 to-orange-600 hover:from-amber-500 hover:to-orange-500 text-white text-xs sm:text-sm font-bold shadow-lg transition-all inline-flex items-center justify-center gap-2 cursor-pointer focus:outline-none focus:ring-2 focus:ring-amber-400"
        >
          <RefreshCw className="h-4 w-4 text-white" />
          <span>Retry Payment</span>
        </button>

        {/* SAFETY & SIMULATION BADGES */}
        <div className="space-y-1.5 pt-1">
          <div className="rounded-lg border border-amber-900/60 bg-amber-950/40 p-2.5 flex items-center gap-2 text-[11px] font-semibold text-amber-300">
            <ShieldCheck className="h-4 w-4 shrink-0 text-amber-400" />
            <span>Simulation — in-app notification only. No email or SMS sent.</span>
          </div>
        </div>
      </div>
    </div>
  );
}
